#include <string>
#include <vector>
#include <math.h>
#include <iostream>
#include <numeric>
#include <algorithm>
#include <stdlib.h>
#include "TH1.h"
#include "TRandom3.h"
#include <glog/logging.h>
#include <fstream>
#include "TCanvas.h"
#include "TApplication.h"
#include "TGraph.h"
#include "TH2.h"
#include "TStyle.h"
#include  <map>
#include "TMath.h"
#include "TFile.h"
#include "TTree.h"
#include "TBranch.h"
#include "TF1.h"
